services:
  - type: web
    name: xVault
    runtime: node
    buildCommand: |
      npm install --include=dev
      npm run fix-permissions
      npx ng build
      npx ng run secure-messenger:server
    startCommand: node dist/secure-messenger/server/server.mjs
